/* Generated By:JavaCC: Do not edit this line. QuartzConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuartzConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int THEN = 4;
  /** RegularExpression Id. */
  int ELSE = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int PUTS = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\"puts\"",
    "<INTEGER>",
    "<STRING>",
    "<IDENTIFIER>",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
  };

}
